### ISSUE TITLE
Overapped Text issue

### ISSUE THREAD

**Issue by hon9g** [sharpfives/the-gems-game#2]
I would like to inform you that there are issues with some letters being cut off or overlapped.
Anyway, thank you for sharing your game.  The graphics are really cute and natural.

![image](https://user-images.githubusercontent.com/26381972/72521055-12d29400-389e-11ea-89c1-1deafe614230.png)

**Comment by ageofadz** [comment]
I was able to replicate this by clicking quickly through dialogue. I second @hon9g on the praise, this game has a great chilled out vibe.

![Screen Shot 2020-01-22 at 11 59 24 PM](https://user-images.githubusercontent.com/20655124/72960426-47998c00-3d73-11ea-8ecc-6bcfb3516b14.png)

**Comment by sharpfives** [comment]
thanks for the bug report and the kind words. I just pushed some changes that should take care of it. let me know if you still see this issue - otherwise i will close this out.
